stages:
  - build-portal
  - trigger_build

before_script:
  - echo $CI_JOB_TOKEN
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

build-portal:
  stage: build-portal
  tags:
    - deploy
  script:
    - "npm install"
    - docker push registry.gitlab.com/gaiaenergy/fitme/portal


trigger_build:
  stage: trigger_build
  tags:
    - deploy
  script:
    - "curl -X POST -F token=aee436b42e2a5cc0494e6139082698 -F ref=develop https://gitlab.com/api/v4/projects/10541514/trigger/pipeline"
