stages:
  - trigger_build


trigger_build:
  stage: trigger_build
  script:
    - "curl -X POST -F token=aee436b42e2a5cc0494e6139082698 -F ref=develop https://gitlab.com/api/v4/projects/10541514/trigger/pipeline"
