stages:
  - trigger_build
  - build-portal
  
before_script:
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

build-portal:
  stage: build-portal
  script: 
   - docker build -t registry.gitlab.com/gaiaenergy/fitme/portal:latest -t registry.gitlab.com/gaiaenergy/fitme/portal:$CI_JOB_ID .
  tags:
    - deploy
  only:
    - develop

trigger_build:
  stage: trigger_build
  tags:
    - deploy
  script:
    - "curl -X POST -F token=aee436b42e2a5cc0494e6139082698 -F ref=develop https://gitlab.com/api/v4/projects/10541514/trigger/pipeline"
