stages:
  - trigger_build


trigger_build:
  stage: trigger_build
  script:
    - "curl -X POST -F token=bec17de7587f0dba5aa0b2c88fc398 -F ref=develop https://gitlab.com/api/v4/projects/10558264/trigger/pipeline"   